/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import control.AdmDatos;
import control.ProductoJpaController;
import java.awt.CardLayout;
import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelo.DatosTablaVenta;
import modelo.MTablaVenta;
import modelo.Producto;

/**
 *
 * @author Hp EliteBook
 */
public class InterfazCajero extends javax.swing.JDialog {
private Producto producto;
private List<Producto> productos;
private ProductoJpaController cProducto;
private List<Producto> productosComprados;
private ArrayList<DatosTablaVenta> datosVentas = new ArrayList<>();
private MTablaVenta modTabVenta;
private BigDecimal Total= new BigDecimal(0), subTotal = new BigDecimal(0);
private final BigDecimal IVA_PORCENTAJE = new BigDecimal("0.16");


    /**
     * Creates new form InterfazCajero
     */
    public InterfazCajero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cProducto = new ProductoJpaController(AdmDatos.getEntityManagerFactory());
        productos = cProducto.findProductoEntities();
        
        inabilitar();
        TablaLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextProducto = new javax.swing.JTextField();
        PanelBotones = new javax.swing.JPanel();
        InicioPanel = new javax.swing.JPanel();
        BotonIniciarVenta = new javax.swing.JButton();
        BotonRetiro = new javax.swing.JButton();
        BotonSupervisor = new javax.swing.JButton();
        BotonSalirInicio = new javax.swing.JButton();
        PanelVenta = new javax.swing.JPanel();
        EfectivoVenta = new javax.swing.JButton();
        DebitoVenta = new javax.swing.JButton();
        CreditoVenta = new javax.swing.JButton();
        CuponVenta = new javax.swing.JButton();
        SalirVenta = new javax.swing.JButton();
        ValeVenta = new javax.swing.JButton();
        PanelSupervisor = new javax.swing.JPanel();
        ReporteParcial = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        SalirSupervisor = new javax.swing.JButton();
        PanelRetiro = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        RegresarRetiro = new javax.swing.JButton();
        PanelDetalles = new javax.swing.JPanel();
        PanelDetalleVentas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaPago = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        PanelDetalleRetiros = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 14)); // NOI18N
        jLabel1.setText("Zapateria MiChingon");

        TextProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextProductoActionPerformed(evt);
            }
        });

        PanelBotones.setLayout(new java.awt.CardLayout());

        BotonIniciarVenta.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonIniciarVenta.setText("Iniciar Venta");
        BotonIniciarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarVentaActionPerformed(evt);
            }
        });

        BotonRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonRetiro.setText("Retiro");
        BotonRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetiroActionPerformed(evt);
            }
        });

        BotonSupervisor.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonSupervisor.setText("Menu Supervisor");
        BotonSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSupervisorActionPerformed(evt);
            }
        });

        BotonSalirInicio.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonSalirInicio.setText("Salir");
        BotonSalirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonIniciarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSalirInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonIniciarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSalirInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotones.add(InicioPanel, "InicioPanel");

        EfectivoVenta.setText("Efectivo");
        EfectivoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfectivoVentaActionPerformed(evt);
            }
        });

        DebitoVenta.setText("Targeta de Debito");

        CreditoVenta.setText("Targeta de Credito");

        CuponVenta.setText("Cupon");

        SalirVenta.setText("Regresar");
        SalirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVentaActionPerformed(evt);
            }
        });

        ValeVenta.setText("Vale por Devolucion");

        javax.swing.GroupLayout PanelVentaLayout = new javax.swing.GroupLayout(PanelVenta);
        PanelVenta.setLayout(PanelVentaLayout);
        PanelVentaLayout.setHorizontalGroup(
            PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreditoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DebitoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValeVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CuponVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EfectivoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelVentaLayout.setVerticalGroup(
            PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(EfectivoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuponVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DebitoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreditoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelVenta, "PanelVenta");

        ReporteParcial.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ReporteParcial.setText("Reporte Parcial");
        ReporteParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteParcialActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton12.setText("Reporte Final");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton13.setText("Ultima Transaccion");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        SalirSupervisor.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        SalirSupervisor.setText("Regresar");
        SalirSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSupervisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSupervisorLayout = new javax.swing.GroupLayout(PanelSupervisor);
        PanelSupervisor.setLayout(PanelSupervisorLayout);
        PanelSupervisorLayout.setHorizontalGroup(
            PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReporteParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSupervisorLayout.setVerticalGroup(
            PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReporteParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalirSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelSupervisor, "PanelSupervisor");

        jButton15.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton15.setText("Agregar Retiro");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton16.setText("Consultar Retiros");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        RegresarRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        RegresarRetiro.setText("Regresar");
        RegresarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRetiroLayout = new javax.swing.GroupLayout(PanelRetiro);
        PanelRetiro.setLayout(PanelRetiroLayout);
        PanelRetiroLayout.setHorizontalGroup(
            PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRetiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRetiroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRetiroLayout.createSequentialGroup()
                        .addGroup(PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegresarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelRetiroLayout.setVerticalGroup(
            PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRetiroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegresarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelRetiro, "PanelRetiro");

        PanelDetalles.setLayout(new java.awt.CardLayout());

        AreaPago.setColumns(20);
        AreaPago.setRows(5);
        AreaPago.setText("Subtotal \nIVA\t\t\t\t\t\t          16%\n--------------------------------------------------------------------------------------------------------------------------\nTotal a pagar:");
        jScrollPane2.setViewportView(AreaPago);

        TablaProducto.setForeground(new java.awt.Color(204, 204, 204));
        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProducto);

        javax.swing.GroupLayout PanelDetalleVentasLayout = new javax.swing.GroupLayout(PanelDetalleVentas);
        PanelDetalleVentas.setLayout(PanelDetalleVentasLayout);
        PanelDetalleVentasLayout.setHorizontalGroup(
            PanelDetalleVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        PanelDetalleVentasLayout.setVerticalGroup(
            PanelDetalleVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetalleVentasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelDetalles.add(PanelDetalleVentas, "card2");

        javax.swing.GroupLayout PanelDetalleRetirosLayout = new javax.swing.GroupLayout(PanelDetalleRetiros);
        PanelDetalleRetiros.setLayout(PanelDetalleRetirosLayout);
        PanelDetalleRetirosLayout.setHorizontalGroup(
            PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        PanelDetalleRetirosLayout.setVerticalGroup(
            PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        PanelDetalles.add(PanelDetalleRetiros, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextProducto))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void TablaLista(){
        TablaProducto.setModel(new MTablaVenta(new ArrayList<>()));
        TablaProducto.getTableHeader().setReorderingAllowed(false);
        TablaProducto.getTableHeader().setResizingAllowed(false);
        TablaProducto.setShowGrid(true); // Asegúrate que las líneas se muestren
        TablaProducto.setGridColor(new Color(45, 45, 45)); // Color gris claro (puedes cambiarlo)
        TablaProducto.getColumnModel().getColumn(0).setPreferredWidth(240); // Descripción
        TablaProducto.getColumnModel().getColumn(1).setPreferredWidth(80);  // Precio
        TablaProducto.getColumnModel().getColumn(2).setPreferredWidth(70);  // Cantidad
        TablaProducto.getColumnModel().getColumn(3).setPreferredWidth(90);  // Descuento
        TablaProducto.getColumnModel().getColumn(4).setPreferredWidth(120); // Subtotal

    }
    public void inabilitar(){
        TextProducto.setEditable(false);
        AreaPago.setEditable(false);
        
    }
    public void Habilitar(){
        TextProducto.setEditable(true);
    }
    
    public void modificarTextArea(){
        BigDecimal iva = subTotal.multiply(IVA_PORCENTAJE); // 16% del subtotal
        Total = subTotal.add(iva); // Total final con IVA incluido
        Total = Total.setScale(2, RoundingMode.HALF_UP);
        
        AreaPago.setText("Subtotal\t\t\t\t\t\t    $"+subTotal+"\n"
                + "IVA\t\t\t\t\t\t          16%\n"
                + "--------------------------------------------------------------------------------------------------------------------------\n"
                + "Total a pagar:\t\t\t\t\t\t   $"+Total);
    }
    
    public void GenerarTicket(){
        
    }
    
    private void BotonIniciarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarVentaActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelVenta"); // o "inicio"
        Habilitar();
    }//GEN-LAST:event_BotonIniciarVentaActionPerformed

    private void BotonSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSupervisorActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelSupervisor"); // o "inicio"
    }//GEN-LAST:event_BotonSupervisorActionPerformed

    private void BotonRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetiroActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelRetiro"); // o "inicio"
    }//GEN-LAST:event_BotonRetiroActionPerformed

    private void ReporteParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteParcialActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PanelReporteVenta(null, true, "María López").setVisible(true);
        setVisible(true);
        
    }//GEN-LAST:event_ReporteParcialActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void TextProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextProductoActionPerformed
        // TODO add your handling code here:
        String entrada = TextProducto.getText().trim();
        if (!entrada.isEmpty()) {
            try {
                int productoIngresado = Integer.parseInt(entrada);
                boolean encontrado = false;

                for (Producto p : productos) {
                    if (p.getIdProducto() == productoIngresado) {
                        DatosTablaVenta dtv = new DatosTablaVenta(p);
                        datosVentas.add(dtv);
                        subTotal = subTotal.add(dtv.getSubtotal());
                        encontrado = true;
                        break; // Producto encontrado, salimos del ciclo
                    }
                }
                if (!encontrado) {
                    JOptionPane.showMessageDialog(null, "Producto no encontrado.");
                }
                TextProducto.setText("");
                modTabVenta = new MTablaVenta(datosVentas);
                TablaProducto.setModel(modTabVenta);
                modificarTextArea();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ID de producto inválido.");
            }
        }
        
    }//GEN-LAST:event_TextProductoActionPerformed

    private void BotonSalirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirInicioActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) ((JDialog) SwingUtilities.getWindowAncestor(BotonSalirInicio)).dispose();
        
    }//GEN-LAST:event_BotonSalirInicioActionPerformed

    private void SalirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVentaActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas Regresar?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION){
            CardLayout cl = (CardLayout)(PanelBotones.getLayout());
            cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        }
        
    }//GEN-LAST:event_SalirVentaActionPerformed

    private void SalirSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSupervisorActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas Regresar?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION){
            CardLayout cl = (CardLayout)(PanelBotones.getLayout());
            cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        }
    }//GEN-LAST:event_SalirSupervisorActionPerformed

    private void RegresarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarRetiroActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas Regresar?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION){
            CardLayout cl = (CardLayout)(PanelBotones.getLayout());
            cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        }
    }//GEN-LAST:event_RegresarRetiroActionPerformed

    private void EfectivoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfectivoVentaActionPerformed
        // TODO add your handling code here:
        GenerarTicket();
        AreaPago.setText("Subtotal\n"
                + "IVA\t\t\t\t\t\t         16%\n"
                + "--------------------------------------------------------------------------------------------------------------------------\n"
                + "Total a pagar:");
        datosVentas.clear();
        modTabVenta = new MTablaVenta(datosVentas);
        TablaProducto.setModel(modTabVenta);
        TextProducto.setText("");
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        Habilitar();
    }//GEN-LAST:event_EfectivoVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            FlatMacDarkLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazCajero dialog = new InterfazCajero(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaPago;
    private javax.swing.JButton BotonIniciarVenta;
    private javax.swing.JButton BotonRetiro;
    private javax.swing.JButton BotonSalirInicio;
    private javax.swing.JButton BotonSupervisor;
    private javax.swing.JButton CreditoVenta;
    private javax.swing.JButton CuponVenta;
    private javax.swing.JButton DebitoVenta;
    private javax.swing.JButton EfectivoVenta;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelDetalleRetiros;
    private javax.swing.JPanel PanelDetalleVentas;
    private javax.swing.JPanel PanelDetalles;
    private javax.swing.JPanel PanelRetiro;
    private javax.swing.JPanel PanelSupervisor;
    private javax.swing.JPanel PanelVenta;
    private javax.swing.JButton RegresarRetiro;
    private javax.swing.JButton ReporteParcial;
    private javax.swing.JButton SalirSupervisor;
    private javax.swing.JButton SalirVenta;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JTextField TextProducto;
    private javax.swing.JButton ValeVenta;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
