/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import control.AdmDatos;
import control.ProductoJpaController;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.FileReader;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.DatosTablaVenta;
import modelo.MTablaVenta;
import modelo.Producto;

/**
 *
 * @author Hp EliteBook
 */
public class InterfazCajero extends javax.swing.JDialog {
    private Producto producto;
    private List<Producto> productos;
    private List<Producto> productosComprados = new ArrayList<>();
    private ProductoJpaController cProducto;
    private ArrayList<DatosTablaVenta> datosVentas = new ArrayList<>();
    private MTablaVenta modTabVenta;
    private BigDecimal Total= new BigDecimal(0), subTotal = new BigDecimal(0), monto = new BigDecimal(0), cantidadPagada = new BigDecimal(0);
    private final BigDecimal IVA_PORCENTAJE = new BigDecimal("0.16");
    private String TipoPago, nombreCajero; 
    private List<String> tiposPagos = new ArrayList<>();
    private List<BigDecimal> pagosParciales = new ArrayList<>() ;
     private BigDecimal efectivo = new BigDecimal(0);
    private BigDecimal cupon = new BigDecimal(0);
    private BigDecimal credito = new BigDecimal(0);
    private BigDecimal debito = new BigDecimal(0);
    private BigDecimal vale = new BigDecimal(0);
    private BigDecimal totalVentas = new BigDecimal(0);
    private int Retiros = 0;
    private Document doc = new Document();
    private String nombreArchivo = "ticket.pdf";  // Se sobrescribirá si ya existe
    /**
     * Creates new form InterfazCajero
     */
    public InterfazCajero(java.awt.Frame parent, boolean modal, String usuarioElegido) {
        super(parent, modal);
        initComponents();
        cProducto = new ProductoJpaController(AdmDatos.getEntityManagerFactory());
        productos = cProducto.findProductoEntities();
        nombreCajero = usuarioElegido;
        efectivo = efectivo.setScale(2, RoundingMode.HALF_UP);
        cupon = cupon.setScale(2, RoundingMode.HALF_UP);
        credito = credito.setScale(2, RoundingMode.HALF_UP);
        debito = debito.setScale(2, RoundingMode.HALF_UP);
        vale = vale.setScale(2, RoundingMode.HALF_UP);
        inabilitar();
        TablaLista();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextProducto = new javax.swing.JTextField();
        PanelBotones = new javax.swing.JPanel();
        InicioPanel = new javax.swing.JPanel();
        BotonIniciarVenta = new javax.swing.JButton();
        BotonRetiro = new javax.swing.JButton();
        BotonSupervisor = new javax.swing.JButton();
        BotonSalirInicio = new javax.swing.JButton();
        PanelVenta = new javax.swing.JPanel();
        EfectivoVenta = new javax.swing.JButton();
        DebitoVenta = new javax.swing.JButton();
        CreditoVenta = new javax.swing.JButton();
        CuponVenta = new javax.swing.JButton();
        SalirVenta = new javax.swing.JButton();
        ValeVenta = new javax.swing.JButton();
        PanelSupervisor = new javax.swing.JPanel();
        ReporteParcial = new javax.swing.JButton();
        ReporteFinal = new javax.swing.JButton();
        UltimaTransaccion = new javax.swing.JButton();
        SalirSupervisor = new javax.swing.JButton();
        PanelRetiro = new javax.swing.JPanel();
        AgregarRetiro = new javax.swing.JButton();
        ConsultarRetiro = new javax.swing.JButton();
        RegresarRetiro = new javax.swing.JButton();
        PanelDetalles = new javax.swing.JPanel();
        PanelDetalleVentas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaPago = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        PanelDetalleRetiros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TMil = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TQuinientos = new javax.swing.JTextField();
        TDoscientos = new javax.swing.JTextField();
        TCien = new javax.swing.JTextField();
        TCincuenta = new javax.swing.JTextField();
        TVeinte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        LTotalRetiro = new javax.swing.JLabel();
        GenerarRetiro = new javax.swing.JButton();
        PanelConsultarRetiros = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 14)); // NOI18N
        jLabel1.setText("Zapateria MiChingon");

        TextProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextProductoActionPerformed(evt);
            }
        });

        PanelBotones.setLayout(new java.awt.CardLayout());

        BotonIniciarVenta.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonIniciarVenta.setText("Iniciar Venta");
        BotonIniciarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarVentaActionPerformed(evt);
            }
        });

        BotonRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonRetiro.setText("Retiro");
        BotonRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetiroActionPerformed(evt);
            }
        });

        BotonSupervisor.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonSupervisor.setText("Menu Supervisor");
        BotonSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSupervisorActionPerformed(evt);
            }
        });

        BotonSalirInicio.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonSalirInicio.setText("Salir");
        BotonSalirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonIniciarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSalirInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonIniciarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSalirInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotones.add(InicioPanel, "InicioPanel");

        EfectivoVenta.setText("Efectivo");
        EfectivoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfectivoVentaActionPerformed(evt);
            }
        });

        DebitoVenta.setText("Targeta de Debito");
        DebitoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitoVentaActionPerformed(evt);
            }
        });

        CreditoVenta.setText("Targeta de Credito");
        CreditoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditoVentaActionPerformed(evt);
            }
        });

        CuponVenta.setText("Cupon");
        CuponVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuponVentaActionPerformed(evt);
            }
        });

        SalirVenta.setText("Regresar");
        SalirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVentaActionPerformed(evt);
            }
        });

        ValeVenta.setText("Vale por Devolucion");
        ValeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValeVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVentaLayout = new javax.swing.GroupLayout(PanelVenta);
        PanelVenta.setLayout(PanelVentaLayout);
        PanelVentaLayout.setHorizontalGroup(
            PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreditoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DebitoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValeVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CuponVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EfectivoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelVentaLayout.setVerticalGroup(
            PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(EfectivoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuponVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DebitoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreditoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelVenta, "PanelVenta");

        ReporteParcial.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ReporteParcial.setText("Reporte Parcial");
        ReporteParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteParcialActionPerformed(evt);
            }
        });

        ReporteFinal.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ReporteFinal.setText("Reporte Final");
        ReporteFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteFinalActionPerformed(evt);
            }
        });

        UltimaTransaccion.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        UltimaTransaccion.setText("Ultima Transaccion");
        UltimaTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimaTransaccionActionPerformed(evt);
            }
        });

        SalirSupervisor.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        SalirSupervisor.setText("Regresar");
        SalirSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSupervisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSupervisorLayout = new javax.swing.GroupLayout(PanelSupervisor);
        PanelSupervisor.setLayout(PanelSupervisorLayout);
        PanelSupervisorLayout.setHorizontalGroup(
            PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReporteParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReporteFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UltimaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSupervisorLayout.setVerticalGroup(
            PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReporteParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReporteFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UltimaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalirSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelSupervisor, "PanelSupervisor");

        AgregarRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        AgregarRetiro.setText("Generar Retiro");
        AgregarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRetiroActionPerformed(evt);
            }
        });

        ConsultarRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ConsultarRetiro.setText("Consultar Retiros");
        ConsultarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarRetiroActionPerformed(evt);
            }
        });

        RegresarRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        RegresarRetiro.setText("Regresar");
        RegresarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRetiroLayout = new javax.swing.GroupLayout(PanelRetiro);
        PanelRetiro.setLayout(PanelRetiroLayout);
        PanelRetiroLayout.setHorizontalGroup(
            PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRetiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRetiroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ConsultarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRetiroLayout.createSequentialGroup()
                        .addGroup(PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegresarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelRetiroLayout.setVerticalGroup(
            PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRetiroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AgregarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConsultarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegresarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelRetiro, "PanelRetiro");

        PanelDetalles.setLayout(new java.awt.CardLayout());

        AreaPago.setColumns(20);
        AreaPago.setRows(5);
        AreaPago.setText("Subtotal \n\n--------------------------------------------------------------------------------------------------------------------------\nTotal a pagar:");
        jScrollPane2.setViewportView(AreaPago);

        TablaProducto.setForeground(new java.awt.Color(204, 204, 204));
        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProducto);

        javax.swing.GroupLayout PanelDetalleVentasLayout = new javax.swing.GroupLayout(PanelDetalleVentas);
        PanelDetalleVentas.setLayout(PanelDetalleVentasLayout);
        PanelDetalleVentasLayout.setHorizontalGroup(
            PanelDetalleVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        PanelDetalleVentasLayout.setVerticalGroup(
            PanelDetalleVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetalleVentasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelDetalles.add(PanelDetalleVentas, "PanelDetalleVentas");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("$1000");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("$500");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("$200");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("$100");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("$20");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("$50");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Generar Nuevo Retiro");

        TMil.setText("0");
        TMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMilActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("------------------------------------------------------------");

        TQuinientos.setText("0");
        TQuinientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TQuinientosActionPerformed(evt);
            }
        });

        TDoscientos.setText("0");
        TDoscientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDoscientosActionPerformed(evt);
            }
        });

        TCien.setText("0");
        TCien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCienActionPerformed(evt);
            }
        });

        TCincuenta.setText("0");
        TCincuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCincuentaActionPerformed(evt);
            }
        });

        TVeinte.setText("0");
        TVeinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVeinteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Total:");

        LTotalRetiro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LTotalRetiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTotalRetiro.setText("$");

        GenerarRetiro.setText("Generar");
        GenerarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDetalleRetirosLayout = new javax.swing.GroupLayout(PanelDetalleRetiros);
        PanelDetalleRetiros.setLayout(PanelDetalleRetirosLayout);
        PanelDetalleRetirosLayout.setHorizontalGroup(
            PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetalleRetirosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TMil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TVeinte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TQuinientos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TDoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221))
            .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addComponent(LTotalRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenerarRetiro))
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel9)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        PanelDetalleRetirosLayout.setVerticalGroup(
            PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addComponent(TMil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TQuinientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TDoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TVeinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(LTotalRetiro))
                    .addComponent(GenerarRetiro))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        PanelDetalles.add(PanelDetalleRetiros, "PanelDetalleRetiros");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel12.setText("Retiros Realizados");

        jButton1.setText("Eliminar");

        jButton2.setText("Modificar");

        javax.swing.GroupLayout PanelConsultarRetirosLayout = new javax.swing.GroupLayout(PanelConsultarRetiros);
        PanelConsultarRetiros.setLayout(PanelConsultarRetirosLayout);
        PanelConsultarRetirosLayout.setHorizontalGroup(
            PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarRetirosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarRetirosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(247, 247, 247))))
            .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jButton1)
                .addGap(77, 77, 77)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelConsultarRetirosLayout.setVerticalGroup(
            PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        PanelDetalles.add(PanelConsultarRetiros, "PanelConsultarRetiros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextProducto))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void TablaLista(){
        TablaProducto.setModel(new MTablaVenta(new ArrayList<>()));
        TablaProducto.getTableHeader().setReorderingAllowed(false);
        TablaProducto.getTableHeader().setResizingAllowed(false);
        TablaProducto.setShowGrid(true); // Asegúrate que las líneas se muestren
        TablaProducto.setGridColor(new Color(45, 45, 45)); // Color gris claro (puedes cambiarlo)
        TablaProducto.getColumnModel().getColumn(0).setPreferredWidth(240); // Descripción
        TablaProducto.getColumnModel().getColumn(1).setPreferredWidth(80);  // Precio
        TablaProducto.getColumnModel().getColumn(2).setPreferredWidth(70);  // Cantidad
        TablaProducto.getColumnModel().getColumn(3).setPreferredWidth(90);  // Descuento
        TablaProducto.getColumnModel().getColumn(4).setPreferredWidth(120); // Subtotal

    }
    
    public void inabilitar(){
        TextProducto.setEditable(false);
        AreaPago.setEditable(false);
    }
    
    public void Habilitar(){ TextProducto.setEditable(true); }
    
    public void asignarPago(BigDecimal cantidad, String tipoPago){
        switch(tipoPago){
                    case "Efectivo": efectivo = efectivo.add(cantidad); break;
                    case "Cupon": ; cupon = cupon.add(cantidad); break;
                    case "Credito":  credito = credito.add(cantidad); break;
                    case "Debito": debito = debito.add(cantidad); break;
                    case "Vale": vale = vale.add(cantidad); break;
        }        
    }
    
    public void modificarTextArea(){
        Total = subTotal;
        AreaPago.setText("Subtotal\t\t\t\t\t\t    $"+subTotal+"\n"
                + "\n"
                + "--------------------------------------------------------------------------------------------------------------------------\n"
                + "Total a pagar:\t\t\t\t\t\t   $"+Total);
    }
    
    public void GenerarTicket(List<String> pagos){
        new PanelTicket(null, true, pagos,pagosParciales, nombreCajero, datosVentas, Total, monto, cantidadPagada);
        cantidadPagada= new BigDecimal(0);
    }
    
    public void Cobro(String tipoPago){
        montoPagado panelAuxiliar = new montoPagado(null, true, subTotal);
        panelAuxiliar.setVisible(true);
        monto = panelAuxiliar.getMonto();
        BigDecimal pagoAuxiliar = monto;
        cantidadPagada = cantidadPagada.add(monto);
        
        if(cantidadPagada.compareTo(Total)<0){
            asignarPago(monto, tipoPago);
            subTotal = subTotal.subtract(monto);
            AreaPago.setText("Subtotal\t\t\t\t\t\t    $"+subTotal+"\n"
                + "\n"
                + "--------------------------------------------------------------------------------------------------------------------------\n"
                + "Total a pagar:\t\t\t\t\t\t   $"+Total);
            tiposPagos.add(tipoPago);
            pagosParciales.add(pagoAuxiliar);
            return;
        } else {
            monto = BigDecimal.ZERO;
            monto = cantidadPagada.subtract(Total);
        }
        
        tiposPagos.add(tipoPago);
        pagosParciales.add(pagoAuxiliar);
        totalVentas = totalVentas.add(Total);
        
        asignarPago(subTotal, tipoPago);
        
        TipoPago = tipoPago;
        GenerarTicket(tiposPagos);
        
        tiposPagos.clear();
        AreaPago.setText("Subtotal\n"
                + "\n"
                + "--------------------------------------------------------------------------------------------------------------------------\n"
                + "Total a pagar:");
        datosVentas.clear();
        modTabVenta = new MTablaVenta(datosVentas);
        TablaProducto.setModel(modTabVenta);
        TextProducto.setText("");
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        Habilitar();
        
        Total = BigDecimal.ZERO;
        subTotal = BigDecimal.ZERO;
        TextProducto.setEditable(false);
    }
    
    private void BotonIniciarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarVentaActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelVenta"); // o "inicio"
        Habilitar();
    }//GEN-LAST:event_BotonIniciarVentaActionPerformed

    private void BotonSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSupervisorActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelSupervisor"); // o "inicio"
    }//GEN-LAST:event_BotonSupervisorActionPerformed

    private void BotonRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetiroActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelRetiro"); // o "inicio"
    }//GEN-LAST:event_BotonRetiroActionPerformed

    private void ReporteParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteParcialActionPerformed
        // TODO add your handling code here:
        List<String> ListaAuxiliar = new ArrayList<>();
        ListaAuxiliar.add(nombreCajero);
        ListaAuxiliar.add(efectivo+"");
        ListaAuxiliar.add(debito+"");
        ListaAuxiliar.add(credito+"");
        ListaAuxiliar.add(cupon+"");
        ListaAuxiliar.add(vale+"");
        ListaAuxiliar.add(Retiros+"");
        ListaAuxiliar.add(totalVentas+"");
        ListaAuxiliar.add("X");
        new PanelReporteVenta(null, true, ListaAuxiliar).setVisible(true);
        
    }//GEN-LAST:event_ReporteParcialActionPerformed

    private void ReporteFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteFinalActionPerformed
        // TODO add your handling code here:
        List<String> ListaAuxiliar = new ArrayList<>();
        ListaAuxiliar.add(nombreCajero);
        ListaAuxiliar.add(efectivo+"");
        ListaAuxiliar.add(debito+"");
        ListaAuxiliar.add(credito+"");
        ListaAuxiliar.add(cupon+"");
        ListaAuxiliar.add(vale+"");
        ListaAuxiliar.add(Retiros+"");
        ListaAuxiliar.add(totalVentas+"");
        ListaAuxiliar.add(" Z");
        
        new PanelReporteVenta(null, true, ListaAuxiliar).setVisible(true);
        
        efectivo = BigDecimal.ZERO;
        debito = BigDecimal.ZERO;
        credito = BigDecimal.ZERO;
        cupon = BigDecimal.ZERO;
        vale = BigDecimal.ZERO;
        Retiros = 0;
        totalVentas = BigDecimal.ZERO;
    }//GEN-LAST:event_ReporteFinalActionPerformed

    private void UltimaTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimaTransaccionActionPerformed
        // TODO add your handling code here:
        try {
            File archivo = new File("C:\\Users\\Hp EliteBook\\OneDrive\\Documents\\Instituto Tecnologico de Oaxaca\\6 Semestre\\Ingeniería de Software\\MiChingon\\ticket.pdf");  // Ruta del PDF ya creado
            if (archivo.exists()) Desktop.getDesktop().open(archivo);  // Abre con el visor de PDF predeterminado
            else System.out.println("El archivo no existe.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UltimaTransaccionActionPerformed

    private void AgregarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRetiroActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(PanelDetalles.getLayout());
        cl.show(PanelDetalles, "PanelDetalleRetiros"); // o "inicio"
        System.out.println(PanelDetalles.getSize());
    }//GEN-LAST:event_AgregarRetiroActionPerformed

    private void ConsultarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarRetiroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ConsultarRetiroActionPerformed

    public void cargarRetirosEnTabla(JTable tabla) {
        String ruta = "retiros.txt";
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

        // Limpia la tabla antes de cargar
        modelo.setRowCount(0);

        try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split("\t");  // separa por tabulación
                if (datos.length == 3) {  // aseguramos que haya 3 campos
                    modelo.addRow(new Object[]{datos[0], datos[1], datos[2]});
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
}
    
    private void TextProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextProductoActionPerformed
        // TODO add your handling code here:
        String entrada = TextProducto.getText().trim();
        if (!entrada.isEmpty()) {
            try {
                int productoIngresado = Integer.parseInt(entrada);
                boolean encontrado = false;
                for (Producto p : productos) {
                    if (p.getIdProducto() == productoIngresado) {
                        DatosTablaVenta dtv = new DatosTablaVenta(p);
                        datosVentas.add(dtv);
                        subTotal = subTotal.add(dtv.getSubtotal());
                        encontrado = true;
                        productosComprados.add(p);
                        break; // Producto encontrado, salimos del ciclo
                    }
                }
                if (!encontrado) {
                    JOptionPane.showMessageDialog(null, "Producto no encontrado.");
                }
                TextProducto.setText("");
                modTabVenta = new MTablaVenta(datosVentas);
                TablaProducto.setModel(modTabVenta);
                modificarTextArea();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ID de producto inválido.");
            }
        }
        
    }//GEN-LAST:event_TextProductoActionPerformed

    private void BotonSalirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirInicioActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) ((JDialog) SwingUtilities.getWindowAncestor(BotonSalirInicio)).dispose();
        
    }//GEN-LAST:event_BotonSalirInicioActionPerformed

    private void SalirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVentaActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas Regresar?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION){
            CardLayout cl = (CardLayout)(PanelBotones.getLayout());
            cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        }
        TextProducto.setEditable(false);        
    }//GEN-LAST:event_SalirVentaActionPerformed

    private void SalirSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSupervisorActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas Regresar?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION){
            CardLayout cl = (CardLayout)(PanelBotones.getLayout());
            cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        }
    }//GEN-LAST:event_SalirSupervisorActionPerformed

    private void RegresarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarRetiroActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas Regresar?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION){
            CardLayout cl = (CardLayout)(PanelBotones.getLayout());
            cl.show(PanelBotones, "InicioPanel"); // o "inicio"
            cl = (CardLayout)(PanelDetalles.getLayout());
            cl.show(PanelDetalles, "PanelDetalleVentas");
        }
    }//GEN-LAST:event_RegresarRetiroActionPerformed

    private void EfectivoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfectivoVentaActionPerformed
        // TODO add your handling code here:
        if (TablaProducto.getRowCount() == 0) return;
        Cobro("Efectivo");
    }//GEN-LAST:event_EfectivoVentaActionPerformed

    private void CuponVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuponVentaActionPerformed
        // TODO add your handling code here:
        if (TablaProducto.getRowCount() == 0) return;
        Cobro("Cupon");
    }//GEN-LAST:event_CuponVentaActionPerformed

    private void DebitoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitoVentaActionPerformed
        // TODO add your handling code here:
        if (TablaProducto.getRowCount() == 0) return;
        Cobro("Debito");
    }//GEN-LAST:event_DebitoVentaActionPerformed

    private void CreditoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditoVentaActionPerformed
        // TODO add your handling code here:
        if (TablaProducto.getRowCount() == 0) return;
        Cobro("Credito");
    }//GEN-LAST:event_CreditoVentaActionPerformed

    private void ValeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValeVentaActionPerformed
        // TODO add your handling code here:
        if (TablaProducto.getRowCount() == 0) return;
        Cobro("Vale");
    }//GEN-LAST:event_ValeVentaActionPerformed

    private void TMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMilActionPerformed

    private void TQuinientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TQuinientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TQuinientosActionPerformed

    private void TDoscientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDoscientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TDoscientosActionPerformed

    private void TCienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCienActionPerformed

    private void TCincuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCincuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCincuentaActionPerformed

    private void TVeinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVeinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TVeinteActionPerformed

    private void GenerarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarRetiroActionPerformed
        // TODO add your handling code here:
        List<String> datosRetiro = new ArrayList<>();
        datosRetiro.add(TMil.getText()); //Cantidad de billetes de 1000
        datosRetiro.add(TQuinientos.getText()); //Cantidad de billetes de 500
        datosRetiro.add(TDoscientos.getText()); //Cantidad de billetes de 200
        datosRetiro.add(TCien.getText()); //Cantidad de billetes de 100
        datosRetiro.add(TCincuenta.getText()); //Cantidad de billetes de 50
        datosRetiro.add(TVeinte.getText()); //Cantidad de billetes de 20
        datosRetiro.add(nombreCajero);
        
        Retiros += Integer.parseInt(datosRetiro.get(0)) * 1000;     // Billetes de 1000
        Retiros += Integer.parseInt(datosRetiro.get(1)) * 500;      // Billetes de 500
        Retiros += Integer.parseInt(datosRetiro.get(2)) * 200;      // Billetes de 200
        Retiros += Integer.parseInt(datosRetiro.get(3)) * 100;      // Billetes de 100
        Retiros += Integer.parseInt(datosRetiro.get(4)) * 50;       // Billetes de 50
        Retiros += Integer.parseInt(datosRetiro.get(5)) * 20;       // Billetes de 20
        datosRetiro.add(Retiros+"");
        new PanelRetiro(null, true, datosRetiro).setVisible(true);
    }//GEN-LAST:event_GenerarRetiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            FlatMacDarkLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazCajero dialog = new InterfazCajero(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarRetiro;
    private javax.swing.JTextArea AreaPago;
    private javax.swing.JButton BotonIniciarVenta;
    private javax.swing.JButton BotonRetiro;
    private javax.swing.JButton BotonSalirInicio;
    private javax.swing.JButton BotonSupervisor;
    private javax.swing.JButton ConsultarRetiro;
    private javax.swing.JButton CreditoVenta;
    private javax.swing.JButton CuponVenta;
    private javax.swing.JButton DebitoVenta;
    private javax.swing.JButton EfectivoVenta;
    private javax.swing.JButton GenerarRetiro;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JLabel LTotalRetiro;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelConsultarRetiros;
    private javax.swing.JPanel PanelDetalleRetiros;
    private javax.swing.JPanel PanelDetalleVentas;
    private javax.swing.JPanel PanelDetalles;
    private javax.swing.JPanel PanelRetiro;
    private javax.swing.JPanel PanelSupervisor;
    private javax.swing.JPanel PanelVenta;
    private javax.swing.JButton RegresarRetiro;
    private javax.swing.JButton ReporteFinal;
    private javax.swing.JButton ReporteParcial;
    private javax.swing.JButton SalirSupervisor;
    private javax.swing.JButton SalirVenta;
    private javax.swing.JTextField TCien;
    private javax.swing.JTextField TCincuenta;
    private javax.swing.JTextField TDoscientos;
    private javax.swing.JTextField TMil;
    private javax.swing.JTextField TQuinientos;
    private javax.swing.JTextField TVeinte;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JTextField TextProducto;
    private javax.swing.JButton UltimaTransaccion;
    private javax.swing.JButton ValeVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}