/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hp EliteBook
 */
public class PanelRetiro extends javax.swing.JDialog {

    /**
     * Creates new form PanelRetiro
     */
    public PanelRetiro(java.awt.Frame parent, boolean modal, List<String> datos) {
        super(parent, modal);
        initComponents();
        String uno = datos.get(0); //1000
        String dos = datos.get(1); //500
        String tres = datos.get(2); //200
        String cuatro = datos.get(3); //100
        String cinco = datos.get(4); //50
        String seis = datos.get(5); //20
        String total = datos.get(6); //total
        String cajero = datos.get(7); // nombre cajero
        
        AreaDatos.setText("\tRETIRO\n-----------------------------------------------\n"
                + "                   Zapateria MiChingon\n"
                + "-----------------------------------------------\n"
                + "Billetes \tCantidad \tSubTotal\n"
                + "$1000\t0\t0\n"
                + "$1000\t0\t0\n"
                + "$500\t0\t0\n"
                + "$200\t0\t0\n"
                + "$100\t0\t0\n"
                + "$50\t0\t0\n"
                + "$20\t0\t0\n"
                + "-----------------------------------------------\n"
                + "Total: \t$0");
        guardarRetiro(LocalDate.now()+"",total, cajero);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                dispose(); // Ahora sí se cierra bien
            }
        });
    }

    public void guardarRetiro(String fecha, String monto, String cajero) {
        String ruta = "retiros.txt";  // archivo donde guardas
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(ruta, true))) { 
            // 'true' para agregar sin borrar contenido
            String linea = fecha + "\t" + monto + "\t" + cajero;
            bw.write(linea);
            bw.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AreaDatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AreaDatos.setColumns(20);
        AreaDatos.setRows(5);
        AreaDatos.setText("\tRETIRO\n-----------------------------------------------\n                   Zapateria MiChingon\n-----------------------------------------------\nBilletes \tCantidad \tSubTotal\n$1000\t0\t0\n$1000\t0\t0\n$500\t0\t0\n$200\t0\t0\n$100\t0\t0\n$50\t0\t0\n$20\t0\t0\n-----------------------------------------------\nTotal: \t$0");
        AreaDatos.setPreferredSize(new java.awt.Dimension(234, 225));
        jScrollPane1.setViewportView(AreaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PanelRetiro dialog = new PanelRetiro(new javax.swing.JFrame(), true, new ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDatos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
